# Generated by Django 4.0.3 on 2022-04-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(default='images/quizes/default_quiz.jpg', upload_to='images/quizes/'),
        ),
        migrations.AlterField(
            model_name='userextras',
            name='profilePic',
            field=models.ImageField(default='images/profiles/default_profile.jpg', upload_to='images/quizes/'),
        ),
    ]
